-- ============================================================
-- Crema — step 1.8: challenges, leaderboard, notifications
--
-- Replaces the last three simulated systems:
--   * challenge entries and votes become rows, not the seedOf(id)
--     hash in challengeEntries()
--   * the weekly leaderboard is computed by a scheduled job into a
--     table, not derived on read
--   * notifications are generated by triggers, so the inbox UI that
--     already exists starts showing real events
--
-- Run after schema.sql and step-1.7.sql. Idempotent.
-- Push *delivery* is Phase 2; this is the data model behind it.
-- ============================================================

-- ============================================================
-- CHALLENGES
-- ============================================================

create table if not exists challenge_joins (
  user_id      uuid references profiles   on delete cascade,
  challenge_id text references challenges on delete cascade,
  created_at   timestamptz default now(),
  primary key (user_id, challenge_id)
);

create table if not exists challenge_entries (
  id           uuid primary key default gen_random_uuid(),
  challenge_id text not null references challenges on delete cascade,
  user_id      uuid not null references profiles   on delete cascade,
  post_id      uuid not null references posts      on delete cascade,
  created_at   timestamptz default now(),
  unique (challenge_id, user_id)          -- one entry each, as the UI assumes
);
create index if not exists challenge_entries_challenge_idx on challenge_entries (challenge_id);

create table if not exists entry_votes (
  user_id    uuid references profiles          on delete cascade,
  entry_id   uuid references challenge_entries on delete cascade,
  created_at timestamptz default now(),
  primary key (user_id, entry_id)
);
create index if not exists entry_votes_entry_idx on entry_votes (entry_id);

-- ============================================================
-- LEADERBOARD
-- ============================================================

create table if not exists leaderboard_weekly (
  week_start date not null,
  user_id    uuid not null references profiles on delete cascade,
  points     int  not null default 0,
  rank       int,
  primary key (week_start, user_id)
);
create index if not exists leaderboard_week_idx on leaderboard_weekly (week_start, rank);

/* Points come from pours, art scores and challenge results — the same
   sentence the app already shows under the leaderboard. Computed, not
   derived on read, so the ordering is stable and cheap to page. */
create or replace function refresh_leaderboard_weekly(target date default null)
returns void language plpgsql security definer set search_path = public as $$
declare wk date := coalesce(target, date_trunc('week', now())::date);
begin
  delete from leaderboard_weekly where week_start = wk;

  insert into leaderboard_weekly (week_start, user_id, points, rank)
  select wk, s.user_id, s.points,
         rank() over (order by s.points desc, s.user_id)
  from (
    select pr.id as user_id,
           coalesce(p.pour_pts,0) + coalesce(l.like_pts,0) + coalesce(c.entry_pts,0) as points
    from profiles pr
    left join (
      select user_id,
             count(*) * 10 + coalesce(sum(round(coalesce(quality,0) * 20)),0) as pour_pts
      from posts
      where created_at >= wk and created_at < wk + 7
      group by user_id
    ) p on p.user_id = pr.id
    left join (
      select po.user_id, count(*) * 2 as like_pts
      from likes lk join posts po on po.id = lk.post_id
      where lk.created_at >= wk and lk.created_at < wk + 7
      group by po.user_id
    ) l on l.user_id = pr.id
    left join (
      select e.user_id, count(*) * 25 + coalesce(sum(v.votes),0) as entry_pts
      from challenge_entries e
      left join (select entry_id, count(*) as votes from entry_votes group by entry_id) v
             on v.entry_id = e.id
      where e.created_at >= wk and e.created_at < wk + 7
      group by e.user_id
    ) c on c.user_id = pr.id
  ) s
  where s.points > 0;
end $$;

-- ============================================================
-- NOTIFICATIONS — generated by triggers, never by the client
-- ============================================================

create or replace function notify_on_like() returns trigger
language plpgsql security definer set search_path = public as $$
declare owner uuid;
begin
  select user_id into owner from posts where id = new.post_id;
  if owner is null or owner = new.user_id then return new; end if;   -- no self-notify
  insert into notifications (user_id, actor_id, type, post_id, body)
  values (owner, new.user_id, 'like', new.post_id, 'liked your pour');
  return new;
end $$;

create or replace function notify_on_comment() returns trigger
language plpgsql security definer set search_path = public as $$
declare owner uuid;
begin
  select user_id into owner from posts where id = new.post_id;
  if owner is null or owner = new.user_id then return new; end if;
  insert into notifications (user_id, actor_id, type, post_id, body)
  values (owner, new.user_id, 'commented on your pour', new.post_id, 'commented on your pour');
  return new;
end $$;

create or replace function notify_on_follow() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into notifications (user_id, actor_id, type, body)
  values (new.followee_id, new.follower_id, 'follow', 'started following you');
  return new;
end $$;

drop trigger if exists likes_notify    on likes;
drop trigger if exists comments_notify on comments;
drop trigger if exists follows_notify  on follows;
create trigger likes_notify    after insert on likes    for each row execute function notify_on_like();
create trigger comments_notify after insert on comments for each row execute function notify_on_comment();
create trigger follows_notify  after insert on follows  for each row execute function notify_on_follow();

-- ============================================================
-- RLS
-- ============================================================

alter table challenge_joins     enable row level security;
alter table challenge_entries   enable row level security;
alter table entry_votes         enable row level security;
alter table leaderboard_weekly  enable row level security;

drop policy if exists "challenge joins are public"   on challenge_joins;
drop policy if exists "users join as themselves"     on challenge_joins;
drop policy if exists "users leave their own"        on challenge_joins;
create policy "challenge joins are public" on challenge_joins for select using (true);
create policy "users join as themselves"   on challenge_joins for insert with check (auth.uid() = user_id);
create policy "users leave their own"      on challenge_joins for delete using (auth.uid() = user_id);

drop policy if exists "entries are public"            on challenge_entries;
drop policy if exists "users enter as themselves"     on challenge_entries;
drop policy if exists "users withdraw their entries"  on challenge_entries;
create policy "entries are public"           on challenge_entries for select using (true);
-- you may only enter a post you actually own
create policy "users enter as themselves"    on challenge_entries for insert
  with check (auth.uid() = user_id and exists (select 1 from posts p where p.id = post_id and p.user_id = auth.uid()));
create policy "users withdraw their entries" on challenge_entries for delete using (auth.uid() = user_id);

drop policy if exists "votes are public"        on entry_votes;
drop policy if exists "users vote as themselves" on entry_votes;
drop policy if exists "users remove their votes" on entry_votes;
create policy "votes are public"         on entry_votes for select using (true);
create policy "users vote as themselves" on entry_votes for insert with check (auth.uid() = user_id);
create policy "users remove their votes" on entry_votes for delete using (auth.uid() = user_id);

drop policy if exists "leaderboard is public" on leaderboard_weekly;
create policy "leaderboard is public" on leaderboard_weekly for select using (true);
-- no client writes: only refresh_leaderboard_weekly() (security definer) fills it

-- ============================================================
-- SCHEDULING  — run this block separately.
--
-- If it errors with "extension pg_cron is not available", enable
-- pg_cron first: Dashboard → Database → Extensions → pg_cron.
-- Everything above works without it; you would just need to call
-- refresh_leaderboard_weekly() yourself.
-- ============================================================
-- create extension if not exists pg_cron;
-- select cron.schedule('crema-leaderboard', '*/15 * * * *',
--                      $$select refresh_leaderboard_weekly()$$);

-- Populate it once now, so the board isn't empty before the first run:
select refresh_leaderboard_weekly();
