#!/usr/bin/env node
/* ============================================================
   Re-apply Crema's own settings to the generated native projects.

     node configure-native.mjs           # patch ios/ and android/
     node configure-native.mjs --check   # are they patched? (exit 1 if not)

   WHY THIS EXISTS — and why it replaces a checklist.

   `ios/` and `android/` are generated by `npx cap add` and are git-ignored:
   they hold absolute paths, build output, and (on iOS) a team id. But a
   generated project is not a *correct* project. Crema needs a dozen
   things Capacitor's template does not know about — the deep links, the
   camera and notification permissions, the launcher icon users already
   have on their home screen, the version, the signing config.

   After step 4.1 those lived in `README.md` as "⚠️ three things were
   edited by hand and will not come back". That is a landmine with a
   timer on it: the day someone runs `cap add android` again — after a
   Capacitor upgrade, on a second machine, in CI — the app silently
   rebuilds without its deep links and with Capacitor's default icon, and
   nothing fails. It just ships wrong.

   So the edits are a script, and the script is idempotent. Run it twice
   and the second run changes nothing. Run `--check` in CI and it says
   whether the working tree's native projects are what the repo intends.
   This is the same rule `gen-sw-assets.mjs` and `sync.mjs` already
   follow: derive it, do not remember it.
   ============================================================ */
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath, pathToFileURL } from 'url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const APP  = path.resolve(HERE, '../..');          // the repo root
const AND  = path.join(HERE, 'android');
const IOS  = path.join(HERE, 'ios/App/App');
const TWA  = path.join(APP, 'platform/android-twa/app/src/main/res');

const CHECK = process.argv.includes('--check');
const problems = [];
const changes  = [];

function need(file){
  if(fs.existsSync(file)) return true;
  problems.push(`missing: ${path.relative(APP, file)} — run \`npx cap add\` first`);
  return false;
}

/* Write only when the bytes actually differ, so --check and the normal
   run share one code path and a no-op run reports nothing. */
function put(file, next, label){
  const prev = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  if(prev === next) return;
  if(CHECK){ problems.push(`out of date: ${label}`); return; }
  fs.mkdirSync(path.dirname(file), { recursive:true });
  fs.writeFileSync(file, next);
  changes.push(label);
}

function putBytes(file, bytes, label){
  const prev = fs.existsSync(file) ? fs.readFileSync(file) : null;
  if(prev && prev.equals(bytes)) return;
  if(CHECK){ problems.push(`out of date: ${label}`); return; }
  fs.mkdirSync(path.dirname(file), { recursive:true });
  fs.writeFileSync(file, bytes);
  changes.push(label);
}

/* ------------------------------------------------------------
   The version, from the git tag — one source of truth.

   `versionName` is the tag without its 'v'. `versionCode` is derived
   from it arithmetically rather than counted, because a counter in a
   file is a thing two branches can disagree about and Play rejects a
   versionCode it has seen before, permanently.

     1.8.0 -> 10800      major*10000 + minor*100 + patch

   ⚠️ Play already has versionCode **5** (the TWA, 1.2.0 on the closed
   alpha track), so any scheme here has to clear it. 10800 does, by a
   wide margin, and it stays monotonic for every plausible version this
   app will ever have. It is deliberately NOT reversible to 1.2.0's 5:
   the TWA's numbering was hand-typed and is not worth preserving.
   ------------------------------------------------------------ */
export function version(){
  let name = '0.0.0';
  try{
    name = execSync('git describe --tags --abbrev=0', { cwd:APP, stdio:['ignore','pipe','ignore'] })
      .toString().trim().replace(/^v/, '');
  }catch(e){
    /* A shallow clone or a tree with no tags. Fall back to package.json
       rather than failing: a developer building locally does not need a
       tag, and CI's --check does not care what the number is. */
    try{ name = JSON.parse(fs.readFileSync(path.join(HERE,'package.json'),'utf8')).version; }catch(_){}
  }
  const [maj=0, min=0, pat=0] = name.split('.').map(n => parseInt(n, 10) || 0);
  return { name, code: maj * 10000 + min * 100 + pat };
}

/* ------------------------------------------------------------
   Marker-delimited splice.

   The first version of this file stripped its own edits with a regex
   over their content and re-inserted them. That is not idempotent: the
   strip left the surrounding blank lines behind and each run added
   another, so `--check` was permanently red and the diff grew forever.

   Markers instead — the same idiom `gen-sw-assets.mjs` uses on sw.js.
   Everything between them is ours and is replaced wholesale; everything
   outside is the generator's and is never touched. `anchor` is where a
   first-time block goes, as a [regex, replacement] pair.

   `comment` is how this file spells a comment, because the markers have
   to be invisible to whatever parses the result: XML for a manifest,
   `#` for a .properties. Getting it wrong writes a literal `<!--` into a
   Gradle property, which Gradle reads as a property named `<!--`. */
function splice(src, name, block, anchor, comment = ['<!-- ', ' -->']){
  const begin = `${comment[0]}@crema:begin ${name}${comment[1]}`;
  const end   = `${comment[0]}@crema:end ${name}${comment[1]}`;
  const body  = `${begin}\n${block}\n${end}`;

  const i = src.indexOf(begin), j = src.indexOf(end);
  if(i >= 0 && j > i) return src.slice(0, i) + body + src.slice(j + end.length);
  return src.replace(anchor[0], anchor[1].replace('@@', body));
}

/* ============================================================
   ANDROID
   ============================================================ */
function android(){
  if(!need(AND)) return;
  const v = version();
  toolchain();

  /* ---------- AndroidManifest: deep links and permissions ----------
     App Links let a tapped https://crema-app.com/#p/<id> open Crema
     instead of Chrome; `autoVerify` makes the system fetch
     /.well-known/assetlinks.json and match this package's SIGNING
     fingerprint against it. That is why 4.3 must re-sign with the
     existing key and why assetlinks.json must not move.

     The custom scheme does the two jobs App Links cannot: the OAuth
     callback (crema://auth, see data/supabase.js) and a push payload's
     deep link, which must open the app that received it. */
  const manifest = path.join(AND, 'app/src/main/AndroidManifest.xml');
  if(need(manifest)){
    let m = fs.readFileSync(manifest, 'utf8');

    const LINKS =
`            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="crema-app.com" />
                <data android:scheme="https" android:host="www.crema-app.com" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="crema" />
            </intent-filter>`;

    const PERMS =
`    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />`;

    m = splice(m, 'links', LINKS,
      [/(\n)(\s*<\/activity>)/, '$1            @@$1$2']);
    m = splice(m, 'perms', PERMS,
      [/(<uses-permission android:name="android\.permission\.INTERNET" \/>)/, '$1\n    @@']);
    put(manifest, m, 'android: deep links + permissions');
  }

  /* ---------- strings: the custom scheme ----------
     Capacitor defaults `custom_url_scheme` to the package name, which
     would make the OAuth callback `com.crema_app.android://auth`. The
     app asks for `crema://auth` (data/supabase.js) and Info.plist
     registers `crema`, so this is the third place that has to agree. */
  const strings = path.join(AND, 'app/src/main/res/values/strings.xml');
  if(need(strings)){
    const s = fs.readFileSync(strings, 'utf8')
      .replace(/(<string name="custom_url_scheme">)[^<]*(<\/string>)/, '$1crema$2');
    put(strings, s, 'android: custom_url_scheme = crema');
  }

  /* ---------- the launcher icon users already have ----------
     This is an in-place update of an app that is on people's home
     screens. The icon must not change, so it is copied from the TWA
     rather than redrawn: same PNGs, same adaptive-icon XML, same plate
     colour (#F5EADA — the cream field, brand guidelines §03; a white
     plate showed as a ring on launchers that mask to a circle). */
  const DENS = ['mdpi','hdpi','xhdpi','xxhdpi','xxxhdpi'];
  for(const d of DENS){
    for(const icon of ['ic_launcher.png','ic_maskable.png']){
      const from = path.join(TWA, `mipmap-${d}`, icon);
      if(!fs.existsSync(from)) continue;
      putBytes(path.join(AND, `app/src/main/res/mipmap-${d}`, icon),
               fs.readFileSync(from), `android: mipmap-${d}/${icon}`);
    }
    /* The notification icon, for the push work in 4.2. */
    const notif = path.join(TWA, `drawable-${d}`, 'ic_notification_icon.png');
    if(fs.existsSync(notif)){
      putBytes(path.join(AND, `app/src/main/res/drawable-${d}`, 'ic_notification_icon.png'),
               fs.readFileSync(notif), `android: drawable-${d}/ic_notification_icon.png`);
    }
  }

  /* Both adaptive-icon entries point at the same artwork. Capacitor
     generates a `_round` variant; leaving it as the template's would
     give round-mask launchers a different icon from square ones. */
  const ADAPTIVE = `<?xml version="1.0" encoding="utf-8"?>
<!-- @crema — configure-native.mjs. The TWA's icon, unchanged: this is an
     in-place update of an app already on people's home screens. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background>
        <layer-list>
            <item android:drawable="@color/ic_launcher_background" />
            <item android:drawable="@mipmap/ic_maskable"
                android:top="8.5dp"
                android:right="8.5dp"
                android:left="8.5dp"
                android:bottom="8.5dp" />
        </layer-list>
    </background>
    <foreground android:drawable="@android:color/transparent" />
</adaptive-icon>
`;
  for(const f of ['ic_launcher.xml','ic_launcher_round.xml']){
    put(path.join(AND, 'app/src/main/res/mipmap-anydpi-v26', f), ADAPTIVE, `android: ${f}`);
  }

  const colors = path.join(AND, 'app/src/main/res/values/ic_launcher_background.xml');
  put(colors, `<?xml version="1.0" encoding="utf-8"?>
<!-- @crema — configure-native.mjs -->
<resources>
    <color name="ic_launcher_background">#F5EADA</color>
</resources>
`, 'android: launcher plate colour');

  /* Capacitor's own colors.xml also declares ic_launcher_background.
     Two resources with one name is a build error, so the template's is
     emptied of it rather than fought with. */
  const capColors = path.join(AND, 'app/src/main/res/values/colors.xml');
  if(fs.existsSync(capColors)){
    const c = fs.readFileSync(capColors, 'utf8');
    if(/ic_launcher_background/.test(c)){
      put(capColors, c.replace(/\s*<color name="ic_launcher_background">[^<]*<\/color>/, ''),
          'android: drop the template plate colour');
    }
  }

  /* ---------- build.gradle: version and signing ----------
     The signing block reads keystore.properties, which is git-ignored
     and holds the upload key's passwords. When that file is absent the
     block is skipped entirely and `assembleDebug` still works — a
     developer without the key can build and run, they just cannot
     produce something Play would accept. */
  const gradle = path.join(AND, 'app/build.gradle');
  if(need(gradle)){
    let g = fs.readFileSync(gradle, 'utf8');
    g = g.replace(/versionCode \d+/,      `versionCode ${v.code}`);
    g = g.replace(/versionName "[^"]*"/,  `versionName "${v.name}"`);

    const SIGN = `
// @crema signing — configure-native.mjs.
// Reads platform/capacitor/keystore.properties, which is git-ignored and
// holds the Play UPLOAD key. ⚠️ That is pwab/signing.keystore, alias
// my-key-alias — NOT android.keystore, and NOT the cert in
// upload-certificate.pem, both of which are superseded. Play rejects a
// bundle signed with anything else. Verify with:
//   apksigner verify --print-certs app-release.aab
// and expect SHA-256 01:1A:73:4E:...:A6:A6
def keystorePropsFile = rootProject.file("../keystore.properties")
android {
    if (keystorePropsFile.exists()) {
        def keystoreProps = new Properties()
        keystoreProps.load(new FileInputStream(keystorePropsFile))
        signingConfigs {
            release {
                storeFile     file(keystoreProps['storeFile'])
                storePassword keystoreProps['storePassword']
                keyAlias      keystoreProps['keyAlias']
                keyPassword   keystoreProps['keyPassword']
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.release
            }
        }
    }
}
`;
    if(!/@crema signing/.test(g)) g = g.trimEnd() + '\n' + SIGN;
    put(gradle, g, `android: version ${v.name} (code ${v.code}) + signing`);
  }
}

/* ============================================================
   iOS — the block step 4.1 added by hand, now reproducible.
   ============================================================ */
function ios(){
  if(!need(IOS)) return;
  const plist = path.join(IOS, 'Info.plist');
  if(!need(plist)) return;
  let p = fs.readFileSync(plist, 'utf8');

  /* Portrait only on iPhone. iPad's separate key keeps all four. */
  p = p.replace(
    /(<key>UISupportedInterfaceOrientations<\/key>\s*<array>)[\s\S]*?(<\/array>)/,
    '$1\n\t\t<string>UIInterfaceOrientationPortrait</string>\n\t$2');

  const BLOCK =
`	<key>NSCameraUsageDescription</key>
	<string>To take a photo of the coffee you just made.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>To add a photo you already took to a pour.</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>com.crema_app.android</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>crema</string>
			</array>
		</dict>
	</array>
	<key>UIBackgroundModes</key>
	<array>
		<string>remote-notification</string>
	</array>`;

  p = splice(p, 'plist', BLOCK, [/(\n<\/dict>\n<\/plist>)/, '\n\t@@$1']);
  put(plist, p, 'ios: permissions, url scheme, background modes, portrait');
}

/* ============================================================
   The command-line half, and it only runs when this file IS the
   command. CI imports version() to assert the versionCode clears the
   TWA's 5; an import must not rewrite the native projects or call
   process.exit() as a side effect. Same guard, same reason, as
   platform/gen-sw-assets.mjs.
   ============================================================ */
/* ============================================================
   The one invariant that is a crash rather than a wrong pixel.

   @capacitor/push-notifications' Android register() calls
   FirebaseMessaging.getInstance(). Without google-services.json in the
   app module that throws, Capacitor's Bridge rethrows it out of a
   Runnable on its task handler, and an uncaught exception on any thread
   ends the process — which is exactly what the Play alpha did when a
   tester tapped "Remind me". src/config.js's NATIVE_PUSH_PLATFORMS is
   the web layer's promise never to make that call, and this is the check
   that the promise still matches the binary.

   Both directions are a failure, and they fail differently:
     · listed but no google-services.json → the app closes on a tap.
     · google-services.json but not listed → push silently does nothing,
       and somebody spends an afternoon on the Edge Function.

   Not part of android(): it patches nothing and it is true or false
   about a file this script must never create — the Firebase config
   carries a project's API keys and is downloaded, not generated. */
function pushCredentials(){
  const gs = fs.existsSync(path.join(AND, 'app/google-services.json'));
  const cfg = fs.readFileSync(path.join(APP, 'src/config.js'), 'utf8');
  const m = cfg.match(/export const NATIVE_PUSH_PLATFORMS\s*=\s*\[([^\]]*)\]/);
  if(!m){
    problems.push('src/config.js no longer exports NATIVE_PUSH_PLATFORMS — data/push.js needs it to know whether it may call register()');
    return;
  }
  const listed = /['"]android['"]/.test(m[1]);
  if(listed && !gs) problems.push(
    "src/config.js lists 'android' in NATIVE_PUSH_PLATFORMS but platform/capacitor/android/app/google-services.json does not exist.\n" +
    "    That combination CLOSES THE APP when someone taps Remind me. Add the file from the Firebase\n" +
    "    project (package com.crema_app.android), or take 'android' back out.");
  if(!listed && gs) problems.push(
    "platform/capacitor/android/app/google-services.json exists but src/config.js does not list 'android'\n" +
    "    in NATIVE_PUSH_PLATFORMS, so the app will never ask for a token and no push can ever arrive.");
}

/* ------------------------------------------------------------
   The JDK Gradle will actually use.

   Capacitor 8 compiles at Java 21 (see android/app/capacitor.build.gradle,
   which cap generates). Gradle finds a toolchain by scanning the places
   macOS registers JDKs — /Library/Java/JavaVirtualMachines and friends —
   and a Homebrew `openjdk@21` is in NONE of them: brew installs it as a
   keg under /opt/homebrew/opt and leaves the symlink into
   /Library/Java to the user, because making it needs sudo.

   So a machine can have exactly the right JDK installed and still fail
   the build with

     Cannot find a Java installation on your machine matching:
     {languageVersion=21, …}. Toolchain download repositories have not
     been configured.

   which reads like "install Java" to somebody who just did. This finds
   it and writes org.gradle.java.home into android/gradle.properties.
   That file is inside the git-ignored android/ tree, so nothing
   machine-specific is ever committed — and it is regenerated by
   `cap add`, which is exactly why this belongs in the script that
   re-applies our settings rather than in a README step.

   Order of preference: an explicit JAVA_HOME that really is 21, then
   macOS's own registry, then the Homebrew keg, then Android Studio's
   bundled runtime. Nothing is installed and nothing is symlinked; if
   none of them is there, say which one line fixes it. */
const JDK = 21;

function jdkHome(){
  const ok = home => {
    if(!home || !fs.existsSync(path.join(home, 'bin/javac'))) return null;
    try{
      const v = execSync(`"${path.join(home,'bin/javac')}" -version`,
        { stdio:['ignore','pipe','pipe'] }).toString();
      return v.includes(`javac ${JDK}.`) ? home : null;
    }catch(e){ return null; }
  };

  const fromEnv = ok(process.env.JAVA_HOME);
  if(fromEnv) return fromEnv;

  try{
    const h = execSync(`/usr/libexec/java_home -v ${JDK}`,
      { stdio:['ignore','pipe','ignore'] }).toString().trim();
    if(ok(h)) return h;
  }catch(e){ /* no such JVM registered — the Homebrew case */ }

  const guesses = [
    `/opt/homebrew/opt/openjdk@${JDK}/libexec/openjdk.jdk/Contents/Home`,
    `/usr/local/opt/openjdk@${JDK}/libexec/openjdk.jdk/Contents/Home`,
    '/Applications/Android Studio.app/Contents/jbr/Contents/Home',
  ];
  for(const g of guesses){ if(ok(g)) return g; }
  return null;
}

function toolchain(){
  const gp = path.join(AND, 'gradle.properties');
  if(!fs.existsSync(gp)) return;
  const home = jdkHome();
  if(!home){
    problems.push(
      `no JDK ${JDK} on this machine, and Capacitor 8 compiles at ${JDK}. Gradle will fail with\n` +
      `    "Cannot find a Java installation … {languageVersion=${JDK}}"\n` +
      `    Fix:  brew install openjdk@${JDK}      (no symlink or sudo needed — this script finds the keg)`);
    return;
  }
  const src = fs.readFileSync(gp, 'utf8');
  put(gp, splice(src, 'jdk',
`# Written by configure-native.mjs. Capacitor 8 compiles at Java ${JDK}, and
# Gradle's toolchain detection does not look inside a Homebrew keg.
# android/ is git-ignored, so this path never leaves this machine.
org.gradle.java.home=${home}`,
    [/\s*$/, '\n\n@@\n'], ['# ', '']), `android: JDK ${JDK} at ${home}`);
}

const isMain = process.argv[1]
  && import.meta.url === pathToFileURL(process.argv[1]).href;
if(!isMain) { /* imported for version(); do nothing */ }
else main();

function main(){
android();
ios();
pushCredentials();

if(problems.length){
  console.error(CHECK ? 'native projects are not configured:' : 'configure-native failed:');
  for(const p of problems) console.error('  ' + p);
  console.error(CHECK ? '\nRun:  node platform/capacitor/configure-native.mjs' : '');
  process.exit(1);
}
const v = version();
if(CHECK) console.log(`native projects are configured — ${v.name} (versionCode ${v.code})`);
else if(changes.length){
  console.log(`configured — ${v.name} (versionCode ${v.code})`);
  for(const c of changes) console.log('  ' + c);
}
else console.log(`already configured — ${v.name} (versionCode ${v.code})`);
}
