#!/usr/bin/env bash
# Re-sign the Gradle-built (unsigned) app bundle with an arbitrary keystore.
#
# Use this when Google Play already has an upload certificate registered that
# differs from ./android.keystore — e.g. a keystore generated by PWABuilder for
# an earlier upload. Play only checks the signing certificate, so signing our
# Bubblewrap bundle with that key is enough; the bundle contents don't change.
#
#   ./resign.sh <keystore> <alias> <store-password> [key-password]
#
# Prints the resulting certificate fingerprints so you can confirm the signature
# matches what Play expects before uploading.
set -euo pipefail

if [ $# -lt 3 ]; then
  sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
  exit 1
fi

KEYSTORE="$1"
ALIAS="$2"
STOREPASS="$3"
KEYPASS="${4:-$3}"

JAVA_HOME="${JAVA_HOME:-/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home}"
KEYTOOL="$JAVA_HOME/bin/keytool"
JARSIGNER="$JAVA_HOME/bin/jarsigner"

cd "$(dirname "$0")"

UNSIGNED="app/build/outputs/bundle/release/app-release.aab"
OUT="app-release-bundle.aab"

if [ ! -f "$UNSIGNED" ]; then
  echo "No Gradle output at $UNSIGNED — run a build first (see README-PLAY.md)." >&2
  exit 1
fi

echo "Signing $UNSIGNED with alias '$ALIAS' from $KEYSTORE"
cp "$UNSIGNED" "$OUT"
"$JARSIGNER" -digestalg SHA-256 -sigalg SHA256withRSA \
  -keystore "$KEYSTORE" -storepass "$STOREPASS" -keypass "$KEYPASS" \
  "$OUT" "$ALIAS"

echo
echo "Signed $OUT with:"
"$KEYTOOL" -printcert -jarfile "$OUT" | grep -E "SHA1:|SHA256:"
echo
echo "Upload $OUT to Play Console. The SHA1 above must match the certificate"
echo "fingerprint Play asks for."
