-- ============================================================
-- The server stops writing emoji.
--
-- Crema carries no emoji since 2026-09-14: the app draws its own glyphs,
-- in its own colours, and an emoji is a picture the phone's font draws
-- instead. The server wrote two, and both reached the lock screen: the
-- medal at the start of the podium body — "🥇 1st place on today's
-- podium", which also sat in the inbox — and the cup in the 8am nudge,
-- "Good morning ☕".
--
-- Four things, each safe to run twice:
--
--   1. podium_check() writes the sentence without the medal. Everything
--      else about it is unchanged. The sentence is the same English the
--      points table has always shown, so every client already carries
--      its German — including the Play build in people's hands, which
--      nothing in this file can update.
--   2. Podium rows already sitting in inboxes lose theirs too, so an old
--      notification and a new one read the same.
--   3. push_i18n is re-seeded in full from src/i18n.de.js — the block
--      below is printed by platform/supabase/gen-push-i18n.mjs, never
--      typed, and `--check` now compares against this file. That is what
--      adds the three medal-less keys. The medal keys step-1.32 seeded are
--      left where they are: nothing writes those bodies any more, and
--      deleting a translation is not worth a statement that can fail.
--   4. push_morning_nudge() says "Good morning" without the cup. Nothing
--      else about it changes, and it is still English on a German phone —
--      a gap 20260831140000_push_reaches_the_phone.sql already files. A
--      nudge is never stored, so there are no old rows to rewrite.
--
-- Tested: local-test/run.sh with every *-test.sql, as CI runs them —
-- podium-test.sql T2 and push-i18n-test.sql T2 for the medal,
-- push-devices-test.sql T8 for the nudge.
-- ============================================================

create or replace function public.podium_check() returns void
    language plpgsql security definer
    set search_path to 'public'
    as $$
declare
  d date := podium_day();
  r record;
  ord text;
begin
  -- Anyone knocked off loses their bookmark, so climbing back announces
  -- itself again.
  delete from podium_places pp
   where pp.day = d
     and not exists (select 1 from podium_top(d) t where t.post_id = pp.post_id);

  -- Yesterday's podium is settled and nothing will re-announce it. Keep a
  -- week for debugging, then let it go.
  delete from podium_places where day < d - 7;

  for r in select * from podium_top(d) loop
    -- The WHERE on the conflict path is what makes this idempotent: an
    -- unchanged place updates nothing, leaves FOUND false, and stays
    -- quiet.
    insert into podium_places (day, post_id, user_id, place)
    values (d, r.post_id, r.user_id, r.place)
    on conflict (day, post_id) do update
       set place = excluded.place, updated_at = now()
     where podium_places.place is distinct from excluded.place;

    if found then
      ord := case r.place when 1 then '1st' when 2 then '2nd' else '3rd' end;
      insert into notifications (user_id, actor_id, type, post_id, body)
      values (r.user_id, null, 'podium', r.post_id,
              ord || ' place on today''s podium');
    end if;
  end loop;
end $$;

-- The rows that already arrived. Only an UPDATE: notifications_push fires
-- AFTER INSERT, so rewriting a body sends nobody a second push.
update notifications
   set body = regexp_replace(body, '^(🥇|🥈|🥉) ', '')
 where type = 'podium'
   and body ~ '^(🥇|🥈|🥉) ';

-- Generated by: node platform/supabase/gen-push-i18n.mjs
insert into push_i18n (key, lang, txt) values
  ('liked your pour', 'de', 'gefällt dein Kaffee'),
  ('commented on your pour', 'de', 'hat deinen Kaffee kommentiert'),
  ('started following you', 'de', 'folgt dir jetzt'),
  ('wants to follow you', 'de', 'möchte dir folgen'),
  ('accepted your follow request', 'de', 'hat deine Anfrage angenommen'),
  ('loved your latte art', 'de', 'mag deine Latte Art'),
  ('loved where you had it', 'de', 'mag den Ort, an dem du ihn hattest'),
  ('loved your choice of coffee', 'de', 'mag deine Kaffeewahl'),
  ('reacted to your pour', 'de', 'hat auf deinen Kaffee reagiert'),
  ('mentioned you in a comment', 'de', 'hat dich in einem Kommentar erwähnt'),
  ('1st place on today''s podium', 'de', '1. Platz auf dem Podium des Tages'),
  ('2nd place on today''s podium', 'de', '2. Platz auf dem Podium des Tages'),
  ('3rd place on today''s podium', 'de', '3. Platz auf dem Podium des Tages'),
  ('Challenge complete: {title} · +{n} points', 'de', 'Challenge geschafft: {title} · +{n} Punkte'),
  ('First coffee in Crema today · +20 points', 'de', 'Erster Kaffee heute in Crema · +20 Punkte'),
  ('poured the first coffee of the day', 'de', 'hat den ersten Kaffee des Tages gemacht'),
  ('poured a coffee', 'de', 'hat einen Kaffee gemacht'),
  ('We looked at what you reported and acted on it. Thank you for flagging it.', 'de', 'Wir haben uns deine Meldung angesehen und gehandelt. Danke, dass du sie geschickt hast.'),
  ('We looked at what you reported and left it up. Thank you for flagging it.', 'de', 'Wir haben uns deine Meldung angesehen und den Beitrag stehen lassen. Danke, dass du sie geschickt hast.'),
  ('Your streak ends tonight', 'de', 'Dein Streak endet heute Abend'),
  ('{n} days so far — one pour keeps it going.', 'de', '{n} Tage bisher — ein Kaffee hält ihn am Leben.'),
  ('Your week in coffee', 'de', 'Deine Kaffeewoche'),
  ('{n} pour', 'de', '{n} Kaffee'),
  ('{n} pours', 'de', '{n} Kaffees'),
  ('{n} like', 'de', '{n} Like'),
  ('{n} likes', 'de', '{n} Likes'),
  ('{n} new follower', 'de', '{n} neuer Follower'),
  ('{n} new followers', 'de', '{n} neue Follower'),
  ('Five Mornings', 'de', 'Fünf Morgen'),
  ('Seven for Seven', 'de', 'Sieben von sieben'),
  ('Before Eight', 'de', 'Vor acht'),
  ('Both Days', 'de', 'Beide Tage'),
  ('Nightcap', 'de', 'Absacker'),
  ('Ten Cups', 'de', 'Zehn Tassen'),
  ('Rosetta Week', 'de', 'Rosetta-Woche'),
  ('Start with a Heart', 'de', 'Fang mit einem Herz an'),
  ('Tulip Season', 'de', 'Tulpenzeit'),
  ('The Swan', 'de', 'Der Schwan'),
  ('Show Your Work', 'de', 'Zeig deine Rechnung'),
  ('Free Pour Five', 'de', 'Fünf frei gegossen'),
  ('Say Something', 'de', 'Sag was dazu'),
  ('Three Bags', 'de', 'Drei Tüten'),
  ('New Territory', 'de', 'Neuland'),
  ('Round the Menu', 'de', 'Einmal quer durch die Karte'),
  ('Out and Out', 'de', 'Raus und weiter'),
  ('Passport', 'de', 'Reisepass'),
  ('Three Roasters', 'de', 'Drei Röstereien'),
  ('Milk Run', 'de', 'Milchrunde'),
  ('Good Company', 'de', 'Gute Gesellschaft')
on conflict (key, lang) do update set txt = excluded.txt;

-- ---------- 4. the 8am nudge, without its cup ----------
-- Copied from 20260831140000_push_reaches_the_phone.sql, its newest
-- definition, with that one word changed. create or replace keeps the
-- grants; the revoke restates them the way that file does.
create or replace function push_morning_nudge()
returns void language plpgsql security definer set search_path = public as $$
declare rows jsonb; n int;
begin
  select coalesce(jsonb_agg(x), '[]'::jsonb) into rows from (
    select push_addr(s) || jsonb_build_object(
             'title', case when r.n > 0 then 'Keep the streak going' else 'Good morning' end,
             'body',  case when r.n > 0
                           then r.n || ' days so far — log today''s and make it ' || (r.n + 1) || '.'
                           else 'Log today''s coffee before it''s just a memory.' end,
             'url',   './',
             'tag',   'morning'
           ) as x
      from push_devices s
      join profiles p on p.id = s.user_id and p.notify_morning
      -- Whether this device's user has already poured today, in their
      -- own timezone. Computed here rather than reused from
      -- streak_at_risk() because that function answers 0 for two
      -- different reasons — "poured today" and "no streak at all" — and
      -- this nudge has to tell them apart to skip the first and still
      -- reach the second.
      cross join lateral (
        select exists (
                 select 1 from posts po
                  where po.user_id = s.user_id
                    and (po.created_at + make_interval(mins => s.tz_offset))::date
                        = (now() + make_interval(mins => s.tz_offset))::date
               ) as poured_today
      ) t
      cross join lateral (select streak_at_risk(s.user_id, s.tz_offset) as n) r
     where not t.poured_today
       and extract(hour from (now() + make_interval(mins => s.tz_offset))) = 8
  ) q;

  n := jsonb_array_length(rows);
  if n > 0 then perform push_send(jsonb_build_object('rows', rows)); end if;
  raise notice 'morning nudges: % device(s)', n;
end $$;

revoke all on function push_morning_nudge() from public, anon, authenticated;
